version: '2'

services:
    blog:
        restart: always
        image: gitlab/gitlab-ce:latest
        expose:
            - "80"
        volumes:
            - ../data/blog/config:/etc/gitlab
            - ../data/blog/logs:/var/log/gitlab
            - ../data/blog/data:/var/opt/gitlab

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        links:
            - blog
